name: A每4小时运行一次

on:
  schedule:
    - cron: '0 */4 * * *'  # 每 4 小时运行一次
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  run-hub-mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Create virtual environment
        run: |
          python -m venv venv
      
      - name: Activate virtual environment and upgrade pip
        run: |
          source venv/bin/activate
          pip install --upgrade pip

      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install -r hub-mirror/requirements.txt
      
      - name: Run Hub Mirror script
        run: |
          source venv/bin/activate
          src: github/6dylan6
          dst: gitee/dslz666
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          python hub-mirror/hubmirror.py --src github/6dylan6 --dst gitee/dslz666 --dst-token ${{ secrets.DST_TOKEN }} --account-type org --src-account-type '' --dst-account-type '' --clone-style https --cache-path /github/workspace/hub-mirror-cache --black-list '' --white-list normal,test,empty --static-list jdpro --force-update true --debug true --timeout 30m --mappings '' --lfs false
